name: Compile and Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    name: Build on windows-latest
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Maven and Java
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: '21'
          java-distribution: 'temurin'
          maven-version: '3.9.9'

      - name: Install Scala
        if: steps.cache-scala.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://downloads.lightbend.com/scala/2.12.20/scala-2.12.20.msi -OutFile scala-2.12.20.msi
          Start-Process msiexec.exe -ArgumentList '/i', 'scala-2.12.20.msi', '/quiet', '/norestart' -Wait
          $env:Path += ';C:\Program Files (x86)\scala\bin'
          [Environment]::SetEnvironmentVariable('Path', $env:Path, [System.EnvironmentVariableTarget]::Machine)

      - name: Compile and Package with Maven
        run: mvn clean package

  build-nix:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-22.04]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Maven and Java
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: '21'
          java-distribution: 'temurin'
          maven-version: '3.9.9'

      - name: Install SDKMAN! and Scala
        if: steps.cache-sdkman.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install scala 2.12.20 || true

      - name: Compile and Package with Maven
        run: mvn clean package
